Webhooks [WIP]
trackmage/trackmage-wordpress-plugin pull request #9
Opened 2019-10-21 15:42 UTC by harbuzniak

2019-10-21 17:36 UTC, karser requested changes

2019-10-21 17:36 UTC, karser commented on tests/wpunit/Endpoint/ShipmentsMapperTest.php
> +                    'originCarrier'          => 'ups',
change it to another carrier, e.g `DHL` so it differs from `self::TEST_CARRIER`

2019-10-21 17:36 UTC, karser commented on tests/wpunit/Endpoint/ShipmentsMapperTest.php
> +        self::assertNotSame($shipmentAfter, $wcShipment);
In the first test case you should make sure it updates everything what we need:
```
self::assertArraySubset([
    'order_id' => $wcOrderId,
    'tracking_number' => 'DHL0123456789',
    'carrier' => 'DHL',
    'trackmage_id' => $trackMageId
], $shipmentAfter);
```

2019-10-21 17:36 UTC, karser commented on src/Webhook/Mappers/AbstractMapper.php
> +            $result = -10;
Just return true or false. We don't care why it can't handle

2019-10-21 17:36 UTC, karser commented on src/Webhook/Mappers/AbstractMapper.php
> +        $workspace = get_option( 'trackmage_workspace' );
this should be cached in a local variable.
```
if ($this->workspace === null) {
    $this->workspace = get_option( 'trackmage_workspace' );
}
//...
```

2019-10-21 17:36 UTC, karser commented on src/Webhook/Mappers/OrdersMapper.php
> +        "updatedAt"         =>  "2019-10-18T09:26:54+00:00",
remove what is not relevant

2019-10-21 17:36 UTC, karser commented on src/Webhook/Mappers/OrdersMapper.php
> +            if(!$this->canHandle() || $trackMageId != $trackmage_order_id)
let's use strict types, `!==`

2019-10-21 17:36 UTC, karser commented on src/Webhook/Mappers/ShipmentsMapper.php
> +        "reviewTotalScore"          =>  "",
remove not relevant

2019-10-22 14:01 UTC, karser requested changes

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/AbstractMapper.php
> +            $result = false;
just `return false;`

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/AbstractMapper.php
> +            $result = false;
just `return false;`

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/AbstractMapper.php
> +            $result = false ;
just `return false;`

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/AbstractMapper.php
> +        return $result;
`return true;`

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/AbstractMapper.php
> +        $result = true;
remove this line

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/OrdersMapper.php
> +        return isset($item['entity']) && $item['entity'] == 'orders';
`===`

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/OrdersMapper.php
> +                return null;
Throw exception here - item not supported

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/ShipmentItemsMapper.php
> +            if($this->canHandle())
`if(!$this->canHandle())`

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/OrderItemsMapper.php
> +                return false;
throw exception here - item not supported

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/ShipmentItemsMapper.php
> +                return false;
Throw exception here - item not supported

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/ShipmentsMapper.php
> +                return false;
Throw exception here - item not supported

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/OrdersMapper.php
> +            if(!$this->canHandle() || $trackMageId !== $trackmage_order_id)
canhandle requires loadEntity, doesn't it?

2019-10-22 14:01 UTC, karser commented on src/Webhook/Mappers/ShipmentItemsMapper.php
> +        return $data;
can you please extract it to a separate function:
`$data['order_item_id'] = $this->getOrderItemIdByTrackMageId($trackmageOrderItemId);`

2019-10-27 09:26 UTC, karser requested changes

2019-10-27 09:26 UTC, karser commented on src/Admin/Admin.php
> +        //add_filter('pre_update_option_trackmage_workspace', [$this, 'select_workspace'], 10, 3);
Remove if it's not needed

2019-10-27 09:26 UTC, karser commented on src/Synchronization/OrderSync.php
> +                            'orderStatus' => ['code' => $this->getTrackMageStatus($order)],
add `title` here. maybe `'orderStatus' => $this->getTrackMageStatus()`, and return ['code', 'title'] in `getTrackMageStatus`.

2019-10-27 09:26 UTC, karser commented on src/Synchronization/OrderSync.php
> +                            'orderStatus' => ['code' => $this->getTrackMageStatus($order)],
add `title` here. maybe `'orderStatus' => $this->getTrackMageStatus()`, and return ['code', 'title'] in `getTrackMageStatus`.

2019-10-27 09:26 UTC, karser commented on src/Synchronization/OrderSync.php
> +        return isset($usedAliases[$status])?$usedAliases['wc-'.$status]:$status;
`isset($usedAliases['wc-'.$status])`

2019-10-27 09:26 UTC, karser commented on src/Webhook/Mappers/AbstractMapper.php
> +    protected function canHandle(){
maybe rename `canHandle` to `validateData`? It throws exception if data is wrong

2019-10-28 10:54 UTC, harbuzniak commented on src/Webhook/Mappers/AbstractMapper.php
> +            $result = false;
changed to throw exception

2019-10-28 10:54 UTC, harbuzniak commented on src/Webhook/Mappers/AbstractMapper.php
> +            $result = false;
changed to throw exception

2019-10-28 10:55 UTC, harbuzniak commented on src/Webhook/Mappers/AbstractMapper.php
> +            $result = false ;
changed to throw exception

2019-10-28 10:59 UTC, harbuzniak commented on src/Webhook/Mappers/OrdersMapper.php
> +            if(!$this->canHandle() || $trackMageId !== $trackmage_order_id)
nope, loadEntity is used for Shipments and ShipmentsItems (or for new repositories)

2019-10-28 17:04 UTC, karser requested changes

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Syncrhonization/OrderSyncTest.php
> +            'orderStatus' => ['code' => 'pending'],
Has to be title as well

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/ShipmentItemsMapperTest.php
> +                0 => "qty"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/ShipmentItemsMapperTest.php
> +                0 => "qty"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/ShipmentItemsMapperTest.php
> +                1 => "orderItem"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/OrdersMapperTest.php
> +                0 => "orderStatus"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/OrdersMapperTest.php
> +                0 => "orderStatus"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/OrdersMapperTest.php
> +                0 => "orderStatus"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/OrdersMapperTest.php
> +                20 => "orderStatus"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/OrderItemsMapperTest.php
> +                2 => "rowTotal"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/OrderItemsMapperTest.php
> +                2 => "rowTotal"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/OrderItemsMapperTest.php
> +                2 => "rowTotal"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on tests/wpunit/Endpoint/OrderItemsMapperTest.php
> +                2 => "rowTotal"
keys can be omitted

2019-10-28 17:04 UTC, karser commented on src/Synchronization/OrderSync.php
> +        return isset($usedAliases['wc-'.$status])?['code'=>$usedAliases['wc-'.$status], 'title' => $aliases[$usedAliases['wc-'.$status]]]:['code'=>$status,'title'=>ucfirst($status)];
One-liner is extremely hard to read. Could you please replace?
```
$wcstatus = 'wc-'.$status;
if (isset($usedAliases[$wcstatus])) {
    return ['code' => $usedAliases[$wcstatus], 'title' => $aliases[$usedAliases[$wcstatus]]];
}
return ['code' => $status,'title' => ucfirst($status)];
```

2019-10-29 09:14 UTC, karser requested changes

2019-10-29 09:14 UTC, karser commented on tests/wpunit/Endpoint/OrdersMapperTest.php
> +        update_option('trackmage_workspace', self::TM_WS_ID);
This option is already defined in `_before`

2019-10-29 09:14 UTC, karser commented on tests/wpunit/Endpoint/OrdersMapperTest.php
> +        //add_option('trackmage_workspace', self::TM_WS_ID);
remove this

2019-10-29 09:14 UTC, karser commented on tests/wpunit/Endpoint/OrdersMapperTest.php
> +        //add_option('trackmage_workspace', self::TM_WS_ID);
remove this

2019-10-29 09:14 UTC, karser commented on tests/wpunit/Endpoint/OrdersMapperTest.php
> +        //add_option('trackmage_workspace', self::TM_WS_ID);
remove this

2019-10-30 16:07 UTC, merged